services:
  - type: web
    name: upskillize-backend
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: ADMIN_EMAIL_1
        sync: false
      - key: ADMIN_EMAIL_2
        sync: false